//
//  NCHSData.swift
//  @NCHS
//
//  Created by Vishal Yalla on 4/13/22.
//

import Foundation
import SwiftUI

let courseArray: [String] = ["BUSINESS AND MARKETING",
               "MARKETING – BEGINNING",
               "MARKETING – ADVANCED",
               "MARKETING MANAGEMENT",
               "RETAIL OPERATIONS/ STUDENT STORE",
               "FAMILY CONSUMER SCIENCE",
               "CHILD DEVELOPMENT",
               "ADULTING 101",
               "INTERIOR DESIGN",
               "FINANCE",
               "STEM:  COMPUTER TECHNOLOGY",
               "WEB DESIGN",
               "MICROSOFT OFFICE CERTIFICATION",
               "INTRODUCTION TO COMPUTER SCIENCE PRINCIPLES",
               "AP COMPUTER SCIENCE PRINCIPLES",
               "(CSE 142) AP COMPUTER SCIENCE A",
               "ADVANCED PROGRAMMING TOPICS 1",
               "(CSE 163) INTERMEDIATE DATA PROGRAMMING",
               "STEM:  ENGINEERING & DESIGN",
               "INTRODUCTION TO ROBOTICS",
               "ADVANCED ROBOTICS",
               "INTRODUCTION TO ENGINEERING DESIGN",
               "AVIATION:  INTRODUCTION TO FLIGHT",
               "METAL FABRICATION",
               "CAD LAB",
               "WELDING AND FABRICATION",
               "BEGINNING SPORTS MEDICINE",
               "ADVANCED SPORTS MEDICINE",
               "MEDICAL PROFESSIONAL ACADEMY (SKILL CENTER PROGRAM)",
               "CONSTRUCTION ACADEMY (SKILL CENTER PROGRAM)",
               "AUTO TECHNOLOGY – BEGINNING",
               "AUTO TECHNOLOGY - ADVANCED (SKILL CENTER PROGRAM)",
               "IB DESIGN TECHNOLOGY SL",
               "IB DESIGN TECHNOLOGY HL",
               "CULINARY ARTS",
               "BAKING & PASTRY ARTS",
               "CAREERS IN EDUCATION",
               "WaNIC CONSORTIUM",
               "OTHER CTE COURSES",
               "LIFESPAN PSYCHOLOGY",
               "AP PSYCHOLOGY",
               "ASB OFFICER CLASS",
               "LIBRARY RESEARCH ASSISTANT",
               "PEER COACHING (ADVOCATE FOR SPECIAL EDUCATION PROGRAM)",
               "9TH GRADE",
               "ENGLISH 9",
               "PRE AP ENGLISH 9",
               "ELL ENGLISH 9",
               "LC ENGLISH 9",
               "10TH GRADE",
               "ENGLISH 10",
               "PRE AP ENGLISH 10",
               "ELL ENGLISH 10",
               "LC ENGLISH 10",
               "11TH GRADE",
               "ENGLISH 11",
               "ELL ENGLISH 11",
               "LC ENGLISH 11",
               "11TH & 12TH GRADE",
               "AP ENGLISH LANGUAGE",
               "AP ENGLISH LITERATURE",
               "CREATIVE WRITING: POETRY & SHORT STORY",
               "COLLEGE PREP ENGLISH: DISCOURSE AND SOCIETY",
               "COLLEGE AND CAREER WRITING",
               "ADVANCED JOURNALISTIC WRITING & MEDIA PRODUCTION",
               "12TH GRADE",
               "ENGLISH 12",
               "(ENGL&101) ENGLISH COMPOSITION I",
               "(ENGL&111) INTRODUCTION TO LITERATURE",
               "ELL ENGLISH 12",
               "LC ENGLISH 12",
               "BEGINNING JOURNALISTIC WRITING",
               "ENGLISH 9 TOPICS",
               "ENGLISH 10 TOPICS",
               "ELA MENTOR",
               "HEALTH",
               "LIFE FITNESS",
               "ADVANCED STRENGTH AND FITNESS",
               "BASEBALL/SOFTBALL",
               "BASKETBALL",
               "OUTDOOR ADVENTURES",
               "RACKET SPORTS",
               "STRENGTH AND FITNESS",
               "TEAM SPORTS",
               "VOLLEYBALL",
               "WALKING FOR FITNESS",
               "YOGA/PILATES",
               "CORE CLASSES",
               "ALGEBRA I",
               "GEOMETRY",
               "ALGEBRA II",
               "ALGEBRA II-TRIGONOMETRY",
               "(MATH & 141) PRECALCULUS I",
               "(MATH & 142) PRECALCULUS II",
               "(MATH & 141 AND 142) PRECALCULUS I AND II",
               "(MATH & 151) CALCULUS I",
               "(MATH& 146) AP STATISTICS",
               "(MATH & 151) CALCULUS I /AP CALC AB",
               "(MATH & 152) CALCULUS II /AP CALC BC",
               "(MATH & 163) CALCULUS III",
               "(MATH & 238) DIFFERENTIAL FUNCTIONS",
               "MATH 1",
               "MATH 2",
               "MATH 3",
               "MATH 4",
               "ALGEBRA II TOPICS",
               "MATH MENTOR",
               "DRAMA",
               "THEATRE ARTS I",
               "THEATRE ARTS II",
               "SCENE STUDIES",
               "TECHNICAL THEATRE",
               "ADVANCED TECHNICAL THEATRE",
               "MUSICAL PERFORMANCE",
               "PLAY PERFORMANCE",
               "VOCAL MUSIC",
               "CHOIR",
               "ADVANCED CHOIR",
               "INSTRUMENTAL MUSIC",
               "JAZZ ENSEMBLE",
               "GUITAR",
               "PIANO LAB",
               "CHAMBER ORCHESTRA",
               "STRING ORCHESTRA",
               "WIND ENSEMBLE",
               "SYMPHONIC BAND",
               "AP MUSIC THEORY",
               "HISTORY OF POPULAR MUSIC",
               "BIOLOGY",
               "AP BIOLOGY",
               "BIOTECHNOLOGY",
               "ADVANCED BIOTECHNOLOGY",
               "AP ENVIRONMENTAL SCIENCE",
               "ZOOLOGY",
               "(ESRM 150) WILDLIFE IN THE MODERN WORLD",
               "PHYSICS",
               "AP PHYSICS 1",
               "AP PHYSICS 2",
               "ASTRONOMY",
               "FORENSICS",
               "CHEMISTRY",
               "AP CHEMISTRY",
               "(BIOL 118) SURVEY OF PHYSIOLOGY",
               "(BIOL 100) INTRODUCTION BIOLOGY:  ADDICTION AND THE BRAIN",
               "SCIENCE MENTOR",
               "SOCIAL STUDIES",
               "9TH OR 10TH GRADE",
               "WORLD HISTORY",
               "AP WORLD HISTORY:  MODERN",
               "11TH GRADE",
               "UNITED STATES HISTORY",
               "AP UNITED STATES HISTORY",
               "CIVICS",
               "CONTEMPORARY WORLD PROBLEMS",
               "AP US GOVERNMENT & POLITICS",
               "FLEXIBLE CREDITS - YEAR LONG",
               "AP HUMAN GEOGRAPHY",
               "AP MACROECONOMICS",
               "AP SEMINAR",
               "AP RESEARCH",
               "ETHNIC STUDIES",
               "INTRO TO ECONOMICS",
               "INTRO TO LAW AND THE JUSTICE SYSTEM",
               "LAW AND SOCIETY",
               "GENERAL EDUCATION CLASSES WITH ACCOMMODATIONS",
               "GENERAL EDUCATION CLASSES WITH MODIFICATIONS",
               "LEARNING CENTER (LC) CLASSES",
               "ACADEMIC LAB CLASSES",
               "CO-TEACHING CLASSES",
               "ASPIRE",
               "FUNCTIONAL SKILLS AND ACADEMICS (FSA) CLASSES",
               "DRAWING / DESIGN",
               "INTERMEDIATE ART",
               "ADVANCED ART",
               "CERAMICS",
               "ADVANCED CERAMICS",
               "AP STUDIO ART:  DRAWING PORTFOLIO",
               "AP STUDIO ART:  2-D DESIGN PORTFOLIO",
               "GRAPHIC DESIGN",
               "ADVANCED GRAPHIC DESIGN",
               "DIGITAL PHOTOGRAPHY",
               "ADVANCED DIGITAL PHOTOGRAPHY",
               "ANNUAL STAFF (YEARBOOK)",
               "ARCHITECTURAL DESIGN LAB",
               "1ST YEAR LANGUAGE",
               "FRENCH 100",
               "GERMAN 100",
               "JAPANESE 100",
               "SPANISH 100",
               "ASL 100 (AMERICAN SIGN LANGUAGE)",
               "2ND YEAR LANGUAGE",
               "FRENCH 200",
               "GERMAN 200",
               "JAPANESE 200",
               "SPANISH 200",
               "ASL 200 (AMERICAN SIGN LANGUAGE)",
               "3RD YEAR LANGUAGE",
               "(FRENCH 103) ELEMENTARY FRENCH (FRENCH III)",
               "(GERM & 123) GERMAN III",
               "(JAPN & 123) JAPANESE III",
               "(SPAN & 123) SPANISH III",
               "ASL 300 (AMERICAN SIGN LANGUAGE)",
               "4TH & 5TH YEAR LANGUAGE",
               "AP FRENCH",
               "AP GERMAN",
               "(JAPN & 221) JAPANESE IV",
               "(SPAN & 221) SPANISH IV",
               "AP SPANISH LANGUAGE",
               "ASL 400 (AMERICAN SIGN LANGUAGE)",
               "COLLEGE READINESS THROUGH AVID 9",
               "COLLEGE READINESS THROUGH AVID 10",
               "COLLEGE READINESS THROUGH AVID 11",
               "COLLEGE READINESS THROUGH AVID 12",
               "AVID MENTOR",
               "LEADERSHIP CLASS",
               "ADVANCED ASB OFFICER CLASS",
               "STUDENT SUCCESS SEMINAR",
               "LINK CREW CLASS",
               "OFFICE ASSISTANTS",
               "TEACHER ASSISTANTS"]



let names = ["Poonam Ahuja",
             "Ima Akpaidem",
             "Carol Anderssohn",
             "Deanna Armstrong",
             "Aidan Bale",
             "Cynda Bambarger",
             "Elizabeth Banning",
             "Raymond Barber",
             "Ian Barnes",
             "Laura Barnes",
             "Andrea Bartleson",
             "Gwen Belden",
             "Bethany Bezanson",
             "Kylee Billings",
             "Florence Booth",
             "Naudia Bosch",
             "Jeff Boselly",
             "Kristin Briley",
             "Sara Brogdon",
             "Sarah Campbell",
             "Angelique Celori",
             "Catherine Christensen",
             "Melanie Damson",
             "Lauren Dandridge",
             "Desiree Diego",
             "Melissa Dupre",
             "Matthew Edgar",
             "Kristin Eis",
             "Chris Estefani",
             "Claire Farr",
             "Maureen Fleischman",
             "Liv Grohn",
             "Melanie Grove",
             "Chase Guymon",
             "Tim Hagerman",
             "Christopher Harrison",
             "Kelly Haupt",
             "Haley Heck",
             "Missy Heeb",
             "Cherie Heltne",
             "Scott Henning",
             "Clark Hermes",
             "Kendra Hoerst",
             "Rachelle Holl",
             "Brady Hood",
             "Shannon Hornoiu",
             "Chad Huffman",
             "Iris Hwang",
             "Mark Isakson",
             "Janani Iyer",
             "Deborah Jacobsen",
             "Melton Jefferson",
             "Teresa Jensen",
             "Siji Joeseph",
             "Emiko Kamitsuna",
             "Subashini Kannan",
             "Casey Kellogg",
             "Jay Kenyon",
             "Rachel Knox",
             "Jillian Lacey",
             "Dawn Lamance",
             "Taylor Larson",
             "Cuong Le",
             "Philip Lee",
             "Calista Legeyt Damm",
             "Craig Lemke",
             "Katie Lidgard",
             "Jennifer Ligot",
             "Vanessa Littrell",
             "Nani Lium",
             "Jessica Lorenz",
             "Emili Manko Levite",
             "Amber Manning",
             "Kimberly Marberg",
             "Brittany Martin",
             "Mayela Martinez",
             "Lee Matheson",
             "De Shon Matthews",
             "Eric McDowell",
             "Rhonda McGee",
             "Calvin McHenry",
             "Sharyn Mehner",
             "Katrina Michel",
             "Joseph Mikkelson",
             "Cody Miller",
             "Saskia Mizushima",
             "Kimberlee Monpas",
             "Moki Mosher",
             "Torrey Myers",
             "Mylinda Nelke",
             "Maria Nelson",
             "Paula Nestico",
             "Tracy Nguyen",
             "Mitchell Novack",
             "Nancy Nygren",
             "Thomas Olsen",
             "Sandra Orellana",
             "Nandita Panda",
             "Sudha Pande",
             "Zoe Parkman",
             "Casey Parvin",
             "Susan Pearson",
             "Ilinda Pennant",
             "Alejandro Perez-cortes",
             "Neetu Philip",
             "Chris Pinder",
             "Robert Plummer",
             "Jennifer Polintan",
             "Katie Porter",
             "Amanda Rainwater",
             "Ariel Reeder",
             "Dhanya Regith",
             "Heather Ribarich",
             "Lawrence Riebs",
             "Joseph Robertson",
             "Ann Romero",
             "William Rosenthal",
             "Michele Rousoff Mesaros",
             "Elina RYALES",
             "Cynthia Savage",
             "Gina Scotti",
             "Tanya Seeley",
             "Christine Serica",
             "Ruiping Sherred",
             "Cortney Simmons",
             "Christy Skurski",
             "Kristi Smith",
             "Nancy Smith Vela",
             "Madison Snyder",
             "Jennifer Spencer",
             "Del Spivey",
             "Lauren Stoddard",
             "Jeff Stride",
             "Pamela Sutton",
             "Spencer Teachout",
             "Mudita Tiwari",
             "Ashley Treuhaft",
             "Kristy Waligorski",
             "Russell Walker",
             "Darin Wallace",
             "Kathleen Wallace",
             "Patty Ward",
             "Jabriel Washington",
             "Scott Weaver",
             "Allison Wells",
             "William Whitmore",
             "Timothy Wicks",
             "Shawn Wilson",
             "Andy Wojcik",
             "CHRISTY Wong",
             "Joshua Wood",
             "Christopher Yu"]


let email = ["pahuja@nsd.org",
             "iakpaidem@nsd.org ",
             "canderssohn@nsd.org",
             "darmstrong@nsd.org ",
             "abale@nsd.org ",
             "cbambarger@nsd.org ",
             "ebanning@nsd.org",
             "rbarber2@nsd.org ",
             "ibarnes@nsd.org ",
             "lbarnes@nsd.org",
             "abartleson@nsd.org ",
             "gbelden@nsd.org",
             "bbezanson@nsd.org",
             "kbillings@nsd.org",
             "fbooth@nsd.org ",
             "nbosch@nsd.org",
             "jboselly@nsd.org",
             "kbriley@nsd.org",
             "sbrogdon@nsd.org",
             "scampbell@nsd.org",
             "acelori@nsd.org ",
             "cchristensen@nsd.org",
             "mdamson@nsd.org ",
             "ldandridge@nsd.org",
             "ddiego@nsd.org ",
             "mdupre@nsd.org ",
             "medgar@nsd.org",
             "keis@nsd.org ",
             "cestefani@nsd.org",
             "cfarr@nsd.org",
             "mfleischman@nsd.org",
             "lgrohn@nsd.org ",
             "mgrove@nsd.org ",
             "cguymon@nsd.org",
             "thagerman@nsd.org ",
             "charrison@nsd.org ",
             "khaupt@nsd.org ",
             "hheck@nsd.org",
             "mheeb@nsd.org ",
             "cheltne@nsd.org",
             "shenning@nsd.org ",
             "chermes@nsd.org ",
             "khoerst@nsd.org",
             "rholl@nsd.org",
             "bhood@nsd.org",
             "shornoiu@nsd.org",
             "chuffman2@nsd.org",
             "ihwang@nsd.org",
             "misakson@nsd.org",
             "jiyer@nsd.org",
             "djacobsen@nsd.org",
             "mjefferson2@nsd.org",
             "tjensen@nsd.org",
             "sjoeseph@nsd.org",
             "ekamitsuna@nsd.org",
             "skannan@nsd.org",
             "ckellogg@nsd.org",
             "jkenyon@nsd.org",
             "rknox@nsd.org",
             "jlacey2@nsd.org",
             "dlamance@nsd.org",
             "tlarson@nsd.org",
             "cle@nsd.org",
             "plee@nsd.org",
             "clegeytdamm@nsd.org",
             "clemke@nsd.org",
             "katielidgard@nsd.org",
             "jligot@nsd.org",
             "vlittrell@nsd.org",
             "nlium@nsd.org",
             "jlorenz@nsd.org",
             "emankolevite@nsd.org",
             "amanning@nsd.org",
             "kmarberg@nsd.org",
             "bmartin@nsd.org",
             "mmartinez@nsd.org",
             "rmatheson@nsd.org",
             "dmatthews@nsd.org",
             "emcdowell@nsd.org",
             "rmcgee@nsd.org",
             "cmchenry@nsd.org",
             "smehner@nsd.org",
             "kmichel@nsd.org",
             "jmikkelson@nsd.org",
             "cmiller4@nsd.org",
             "smizushima@nsd.org",
             "kmonpas@nsd.org",
             "mmosher@nsd.org",
             "tmyers@nsd.org",
             "mnelke@nsd.org",
             "mnelson5@nsd.org",
             "pnestico@nsd.org",
             "tnguyen2@nsd.org",
             "mnovack@nsd.org",
             "nnygren@nsd.org",
             "tolsen2@nsd.org",
             "sorellana@nsd.org",
             "npanda@nsd.org",
             "spande@nsd.org",
             "zparkman@nsd.org",
             "cparvin@nsd.org",
             "spearson@nsd.org",
             "ipennant@nsd.org",
             "aperezcortes@nsd.org",
             "nphilip@nsd.org",
             "cpinder@nsd.org",
             "rplummer@nsd.org",
             "jpolintan@nsd.org",
             "kporter@nsd.org",
             "arainwater@nsd.org",
             "areeder@nsd.org",
             "dregith@nsd.org",
             "hribarich@nsd.org",
             "lriebs@nsd.org",
             "jrobertson@nsd.org",
             "aromero@nsd.org",
             "wrosenthal@nsd.org",
             "mrousoffmesaros@nsd.org",
             "eryales@nsd.org",
             "csavage2@nsd.org",
             "gscotti@nsd.org",
             "tseeley@nsd.org",
             "cserica@nsd.org",
             "rsherred@nsd.org",
             "csimmons@nsd.org",
             "cskurski@nsd.org",
             "ksmith8@nsd.org",
             "nvela@nsd.org",
             "msnyder@nsd.org",
             "jspencer@nsd.org",
             "dspivey@nsd.org",
             "lstoddard@nsd.org",
             "jstride@nsd.org",
             "psutton@nsd.org",
             "steachout@nsd.org",
             "mtiwari@nsd.org",
             "atreuhaft@nsd.org",
             "kwaligorski@nsd.org",
             "rwalker@nsd.org",
             "dwallace@nsd.org",
             "kwallace@nsd.org",
             "pward@nsd.org",
             "jwashington@nsd.org",
             "sweaver@nsd.org",
             "awells@nsd.org",
             "wwhitmore@nsd.org",
             "twicks@nsd.org",
             "swilson@nsd.org",
             "awojcik@nsd.org",
             "cwong@nsd.org",
             "jwood@nsd.org",
             "cyu@nsd.org"]

var staff_directory: [StaffDirectory] = [
    StaffDirectory(name: "Poonam Ahuja", email: "pahuja@nsd.org"),
    StaffDirectory(name: "Ima Akpaidem", email: "iakpaidem@nsd.org "),
    StaffDirectory(name: "Carol Anderssohn", email: "canderssohn@nsd.org"),
    StaffDirectory(name: "Deanna Armstrong", email: "darmstrong@nsd.org "),
    StaffDirectory(name: "Aidan Bale", email: "abale@nsd.org "),
    StaffDirectory(name: "Cynda Bambarger", email: "cbambarger@nsd.org "),
    StaffDirectory(name: "Elizabeth Banning", email: "ebanning@nsd.org"),
    StaffDirectory(name: "Raymond Barber", email: "rbarber2@nsd.org "),
    StaffDirectory(name: "Ian Barnes", email: "ibarnes@nsd.org "),
    StaffDirectory(name: "Laura Barnes", email: "lbarnes@nsd.org"),
    StaffDirectory(name: "Andrea Bartleson", email: "abartleson@nsd.org "),
    StaffDirectory(name: "Gwen Belden", email: "gbelden@nsd.org"),
    StaffDirectory(name: "Bethany Bezanson", email: "bbezanson@nsd.org"),
    StaffDirectory(name: "Kylee Billings", email: "kbillings@nsd.org"),
    StaffDirectory(name: "Florence Booth", email: "fbooth@nsd.org "),
    StaffDirectory(name: "Naudia Bosch", email: "nbosch@nsd.org"),
    StaffDirectory(name: "Jeff Boselly", email: "jboselly@nsd.org"),
    StaffDirectory(name: "Kristin Briley", email: "kbriley@nsd.org"),
    StaffDirectory(name: "Sara Brogdon", email: "sbrogdon@nsd.org"),
    StaffDirectory(name: "Sarah Campbell", email: "scampbell@nsd.org"),
    StaffDirectory(name: "Angelique Celori", email: "acelori@nsd.org "),
    StaffDirectory(name: "Catherine Christensen", email: "cchristensen@nsd.org"),
    StaffDirectory(name: "Melanie Damson", email: "mdamson@nsd.org "),
    StaffDirectory(name: "Lauren Dandridge", email: "ldandridge@nsd.org"),
    StaffDirectory(name: "Desiree Diego", email: "ddiego@nsd.org "),
    StaffDirectory(name: "Melissa Dupre", email: "mdupre@nsd.org "),
    StaffDirectory(name: "Matthew Edgar", email: "medgar@nsd.org"),
    StaffDirectory(name: "Kristin Eis", email: "keis@nsd.org "),
    StaffDirectory(name: "Chris Estefani", email: "cestefani@nsd.org"),
    StaffDirectory(name: "Claire Farr", email: "cfarr@nsd.org"),
    StaffDirectory(name: "Maureen Fleischman", email: "mfleischman@nsd.org"),
    StaffDirectory(name: "Liv Grohn", email: "lgrohn@nsd.org "),
    StaffDirectory(name: "Melanie Grove", email: "mgrove@nsd.org "),
    StaffDirectory(name: "Chase Guymon", email: "cguymon@nsd.org"),
    StaffDirectory(name: "Tim Hagerman", email: "thagerman@nsd.org "),
    StaffDirectory(name: "Christopher Harrison", email: "charrison@nsd.org "),
    StaffDirectory(name: "Kelly Haupt", email: "khaupt@nsd.org "),
    StaffDirectory(name: "Haley Heck", email: "hheck@nsd.org"),
    StaffDirectory(name: "Missy Heeb", email: "mheeb@nsd.org "),
    StaffDirectory(name: "Cherie Heltne", email: "cheltne@nsd.org"),
    StaffDirectory(name: "Scott Henning", email: "shenning@nsd.org "),
    StaffDirectory(name: "Clark Hermes", email: "chermes@nsd.org "),
    StaffDirectory(name: "Kendra Hoerst", email: "khoerst@nsd.org"),
    StaffDirectory(name: "Rachelle Holl", email: "rholl@nsd.org"),
    StaffDirectory(name: "Brady Hood", email: "bhood@nsd.org"),
    StaffDirectory(name: "Shannon Hornoiu", email: "shornoiu@nsd.org"),
    StaffDirectory(name: "Chad Huffman", email: "chuffman2@nsd.org"),
    StaffDirectory(name: "Iris Hwang", email: "ihwang@nsd.org"),
    StaffDirectory(name: "Mark Isakson", email: "misakson@nsd.org"),
    StaffDirectory(name: "Janani Iyer", email: "jiyer@nsd.org"),
    StaffDirectory(name: "Deborah Jacobsen", email: "djacobsen@nsd.org"),
    StaffDirectory(name: "Melton Jefferson", email: "mjefferson2@nsd.org"),
    StaffDirectory(name: "Teresa Jensen", email: "tjensen@nsd.org"),
    StaffDirectory(name: "Siji Joeseph", email: "sjoeseph@nsd.org"),
    StaffDirectory(name: "Emiko Kamitsuna", email: "ekamitsuna@nsd.org"),
    StaffDirectory(name: "Subashini Kannan", email: "skannan@nsd.org"),
    StaffDirectory(name: "Casey Kellogg", email: "ckellogg@nsd.org"),
    StaffDirectory(name: "Jay Kenyon", email: "jkenyon@nsd.org"),
    StaffDirectory(name: "Rachel Knox", email: "rknox@nsd.org"),
    StaffDirectory(name: "Jillian Lacey", email: "jlacey2@nsd.org"),
    StaffDirectory(name: "Dawn Lamance", email: "dlamance@nsd.org"),
    StaffDirectory(name: "Taylor Larson", email: "tlarson@nsd.org"),
    StaffDirectory(name: "Cuong Le", email: "cle@nsd.org"),
    StaffDirectory(name: "Philip Lee", email: "plee@nsd.org"),
    StaffDirectory(name: "Calista Legeyt Damm", email: "clegeytdamm@nsd.org"),
    StaffDirectory(name: "Craig Lemke", email: "clemke@nsd.org"),
    StaffDirectory(name: "Katie Lidgard", email: "katielidgard@nsd.org"),
    StaffDirectory(name: "Jennifer Ligot", email: "jligot@nsd.org"),
    StaffDirectory(name: "Vanessa Littrell", email: "vlittrell@nsd.org"),
    StaffDirectory(name: "Nani Lium", email: "nlium@nsd.org"),
    StaffDirectory(name: "Jessica Lorenz", email: "jlorenz@nsd.org"),
    StaffDirectory(name: "Emili Manko Levite", email: "emankolevite@nsd.org"),
    StaffDirectory(name: "Amber Manning", email: "amanning@nsd.org"),
    StaffDirectory(name: "Kimberly Marberg", email: "kmarberg@nsd.org"),
    StaffDirectory(name: "Brittany Martin", email: "bmartin@nsd.org"),
    StaffDirectory(name: "Mayela Martinez", email: "mmartinez@nsd.org"),
    StaffDirectory(name: "Lee Matheson", email: "rmatheson@nsd.org"),
    StaffDirectory(name: "De Shon Matthews", email: "dmatthews@nsd.org"),
    StaffDirectory(name: "Eric McDowell", email: "emcdowell@nsd.org"),
    StaffDirectory(name: "Rhonda McGee", email: "rmcgee@nsd.org"),
    StaffDirectory(name: "Calvin McHenry", email: "cmchenry@nsd.org"),
    StaffDirectory(name: "Sharyn Mehner", email: "smehner@nsd.org"),
    StaffDirectory(name: "Katrina Michel", email: "kmichel@nsd.org"),
    StaffDirectory(name: "Joseph Mikkelson", email: "jmikkelson@nsd.org"),
    StaffDirectory(name: "Cody Miller", email: "cmiller4@nsd.org"),
    StaffDirectory(name: "Saskia Mizushima", email: "smizushima@nsd.org"),
    StaffDirectory(name: "Kimberlee Monpas", email: "kmonpas@nsd.org"),
    StaffDirectory(name: "Moki Mosher", email: "mmosher@nsd.org"),
    StaffDirectory(name: "Torrey Myers", email: "tmyers@nsd.org"),
    StaffDirectory(name: "Mylinda Nelke", email: "mnelke@nsd.org"),
    StaffDirectory(name: "Maria Nelson", email: "mnelson5@nsd.org"),
    StaffDirectory(name: "Paula Nestico", email: "pnestico@nsd.org"),
    StaffDirectory(name: "Tracy Nguyen", email: "tnguyen2@nsd.org"),
    StaffDirectory(name: "Mitchell Novack", email: "mnovack@nsd.org"),
    StaffDirectory(name: "Nancy Nygren", email: "nnygren@nsd.org"),
    StaffDirectory(name: "Thomas Olsen", email: "tolsen2@nsd.org"),
    StaffDirectory(name: "Sandra Orellana", email: "sorellana@nsd.org"),
    StaffDirectory(name: "Nandita Panda", email: "npanda@nsd.org"),
    StaffDirectory(name: "Sudha Pande", email: "spande@nsd.org"),
    StaffDirectory(name: "Zoe Parkman", email: "zparkman@nsd.org"),
    StaffDirectory(name: "Casey Parvin", email: "cparvin@nsd.org"),
    StaffDirectory(name: "Susan Pearson", email: "spearson@nsd.org"),
    StaffDirectory(name: "Ilinda Pennant", email: "ipennant@nsd.org"),
    StaffDirectory(name: "Alejandro Perez-cortes", email: "aperezcortes@nsd.org"),
    StaffDirectory(name: "Neetu Philip", email: "nphilip@nsd.org"),
    StaffDirectory(name: "Chris Pinder", email: "cpinder@nsd.org"),
    StaffDirectory(name: "Robert Plummer", email: "rplummer@nsd.org"),
    StaffDirectory(name: "Jennifer Polintan", email: "jpolintan@nsd.org"),
    StaffDirectory(name: "Katie Porter", email: "kporter@nsd.org"),
    StaffDirectory(name: "Amanda Rainwater", email: "arainwater@nsd.org"),
    StaffDirectory(name: "Ariel Reeder", email: "areeder@nsd.org"),
    StaffDirectory(name: "Dhanya Regith", email: "dregith@nsd.org"),
    StaffDirectory(name: "Heather Ribarich", email: "hribarich@nsd.org"),
    StaffDirectory(name: "Lawrence Riebs", email: "lriebs@nsd.org"),
    StaffDirectory(name: "Joseph Robertson", email: "jrobertson@nsd.org"),
    StaffDirectory(name: "Ann Romero", email: "aromero@nsd.org"),
    StaffDirectory(name: "William Rosenthal", email: "wrosenthal@nsd.org"),
    StaffDirectory(name: "Michele Rousoff Mesaros", email: "mrousoffmesaros@nsd.org"),
    StaffDirectory(name: "Elina RYALES", email: "eryales@nsd.org"),
    StaffDirectory(name: "Cynthia Savage", email: "csavage2@nsd.org"),
    StaffDirectory(name: "Gina Scotti", email: "gscotti@nsd.org"),
    StaffDirectory(name: "Tanya Seeley", email: "tseeley@nsd.org"),
    StaffDirectory(name: "Christine Serica", email: "cserica@nsd.org"),
    StaffDirectory(name: "Ruiping Sherred", email: "rsherred@nsd.org"),
    StaffDirectory(name: "Cortney Simmons", email: "csimmons@nsd.org"),
    StaffDirectory(name: "Christy Skurski", email: "cskurski@nsd.org"),
    StaffDirectory(name: "Kristi Smith", email: "ksmith8@nsd.org"),
    StaffDirectory(name: "Nancy Smith Vela", email: "nvela@nsd.org"),
    StaffDirectory(name: "Madison Snyder", email: "msnyder@nsd.org"),
    StaffDirectory(name: "Jennifer Spencer", email: "jspencer@nsd.org"),
    StaffDirectory(name: "Del Spivey", email: "dspivey@nsd.org"),
    StaffDirectory(name: "Lauren Stoddard", email: "lstoddard@nsd.org"),
    StaffDirectory(name: "Jeff Stride", email: "jstride@nsd.org"),
    StaffDirectory(name: "Pamela Sutton", email: "psutton@nsd.org"),
    StaffDirectory(name: "Spencer Teachout", email: "steachout@nsd.org"),
    StaffDirectory(name: "Mudita Tiwari", email: "mtiwari@nsd.org"),
    StaffDirectory(name: "Ashley Treuhaft", email: "atreuhaft@nsd.org"),
    StaffDirectory(name: "Kristy Waligorski", email: "kwaligorski@nsd.org"),
    StaffDirectory(name: "Russell Walker", email: "rwalker@nsd.org"),
    StaffDirectory(name: "Darin Wallace", email: "dwallace@nsd.org"),
    StaffDirectory(name: "Kathleen Wallace", email: "kwallace@nsd.org"),
    StaffDirectory(name: "Patty Ward", email: "pward@nsd.org"),
    StaffDirectory(name: "Jabriel Washington", email: "jwashington@nsd.org"),
    StaffDirectory(name: "Scott Weaver", email: "sweaver@nsd.org"),
    StaffDirectory(name: "Allison Wells", email: "awells@nsd.org"),
    StaffDirectory(name: "William Whitmore", email: "wwhitmore@nsd.org"),
    StaffDirectory(name: "Timothy Wicks", email: "twicks@nsd.org"),
    StaffDirectory(name: "Shawn Wilson", email: "swilson@nsd.org"),
    StaffDirectory(name: "Andy Wojcik", email: "awojcik@nsd.org"),
    StaffDirectory(name: "CHRISTY Wong", email: "cwong@nsd.org"),
    StaffDirectory(name: "Joshua Wood", email: "jwood@nsd.org"),
    StaffDirectory(name: "Christopher Yu", email: "cyu@nsd.org")]

